DROP DATABASE IF EXISTS lab_mysql;
CREATE DATABASE lab_mysql;
USE lab_mysql;

--  CREATE CARS TABLE

CREATE TABLE cars (
ID1 INT PRIMARY KEY,
VIN VARCHAR(40),
manufacturer VARCHAR(40) NOT NULL,
model VARCHAR(40) NOT NULL,
year INT,
colour VARCHAR(40) NOT NULL 
);

CREATE TABLE customers (
ID2 INT PRIMARY KEY,
customer_id INT,
name VARCHAR(40) NOT NULL,
phone_number VARCHAR(40) NOT NULL,
email VARCHAR(40) NOT NULL,
address VARCHAR(40) NOT NULL,
city VARCHAR(40) NOT NULL,
state VARCHAR(40) NOT NULL,
country VARCHAR(40) NOT NULL,
post_code VARCHAR(40)
);

CREATE TABLE salesperson (
ID3 INT PRIMARY KEY,
staff_id INT,
name VARCHAR(40) NOT NULL,
company_store VARCHAR(40) NOT NULL
);

CREATE TABLE invoices (
ID4 INT PRIMARY KEY,
invoice_number INT, 
date DATE,
cars INT,
customers INT,
salesperson INT
);

ALTER TABLE invoices 
ADD FOREIGN KEY (cars) 
REFERENCES cars(ID1) 
ON DELETE CASCADE;

ALTER TABLE invoices 
ADD FOREIGN KEY (customers) 
REFERENCES customers(ID2) 
ON DELETE CASCADE;

ALTER TABLE invoices 
ADD FOREIGN KEY (salesperson) 
REFERENCES salesperson(ID3) 
ON DELETE CASCADE;
